name = "Create Astral"
author = "Laskyyy"
version = "v2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0daeb549b2c3505c254cde6c3c9b8190efed90fc7faaddee154a09348859cfe7"

[versions]
fabric = "0.16.3"
minecraft = "1.18.2"
